### ISSUE TITLE
Handle error when there is not a tracked branch set

### ISSUE THREAD

**Issue by llosimura** [tagoro9/fotingo#1]
It should handle nicely when the current branch has not a remote tracked branch set.

**Comment by tagoro9** [comment]
The code is supposed to push the latest branch to the remote, but it hasn't been implemented yet. I agree that in the meantime, this error should be handled in a better way.

**Comment by tagoro9** [comment]
`pushBranchToGithub` function is now implemented and this if fixed. Implemented in 7ac254bfb52536326039b2278090e1b07951bf7b.
