### ISSUE TITLE
Files not in the index don't get added to the stash

### ISSUE THREAD

**Issue by llosimura** [tagoro9/fotingo#19]
If there are new files, not added to the index, before doing a `fotingo start` they don't get add to the stash and the changes are lost.

**Comment by tagoro9** [comment]
I'm looking at the code that creates the stash and it is doing:

```JS
Git.Stash.save(
  debugCurried('git', 'Stashing changes', repository),
  repository.defaultSignature(),
  `auto generated stash by ${app.name}`,
   Git.Stash.FLAGS.INCLUDE_UNTRACKED
)
```

Also, when I check the files contained in the stash. I the stash was created with untracked files, they are still there. Showing the untracked files inside a stash is kind of tricky:

```bash
git ls-tree stash@{0}^3 --name-only
```

Let me know if you still have this issue.

**Comment by llosimura** [comment]
Awesome!
