### ISSUE TITLE
Add a command to update base branch

### ISSUE THREAD

**Issue by carlosmuvi** [tagoro9/fotingo#34]
It could be useful to have a quick way to change the base branch, for example, when you're working with integration branches and want to branch off them.

- It could be a parameter in the existing commands (`fotingo start ISSUE-X -b "branch-name"`)
- A config command could be added to easily modify the `.fotingo` config file  (`fotingo config -b "branch-name"`)

**Comment by tagoro9** [comment]
This has now been implemented. The `start` command now accepts a `-b` option that allows you to overwrite the base branch to be used. 

Now I'm thinking that this probably needs to be added to the `review` command too.
