### ISSUE TITLE
Branch name created as with "undefined/" prefix

### ISSUE THREAD

**Issue by alanpearce** [tagoro9/fotingo#38]
I wanted to `start` an issue of type _Improvement_. This created a branch name like "undefined/XXXX-1234…"

Looking at [git/util.js](https://github.com/tagoro9/fotingo/blob/master/src/git/util.js), it seems as though the `ISSUE_TYPES` mapping doesn't handle this and doesn't have a fallback.

I see a few ways to solve this:

- Add a fallback (perhaps a dynamic one, to the first character of the issue type, lowercased)
- Move `ISSUE_TYPES` into user configuration
- A hybrid of the two above:
  1. Query JIRA issue types
  2. Take the properties from the current `ISSUE_TYPES` that match those from JIRA
  3. For the rest, create a mapping to the first character, lowercased (or some other logic)
  4. Save to configuration
- Allow the branch name format to be configured, such that the issue type prefix could be removed. This seems like a bit more work though.

I can work on this myself if that's helpful (I'm familiar with Ramda), I would just like to know which approach is preferred.

**Comment by tagoro9** [comment]
Thanks for taking the time to create these issues! 

> Allow the branch name format to be configured, such that the issue type prefix could be removed. This seems like a bit more work though.

I think this would be the optimal solution: allow users to define templates for branch names or pr content with certain data that is passed to those templates. Something like:

```JSON
"templates": {
  "branch": "${issueType}/${issueId}_${issueDescription}"
}
```

But as you mention, this may take a little longer, so for now, I think the other solution would be better: 

* Move `ISSUE_TYPES` to configuration.
* When initializing, check that `ISSUE_TYPES` are present. If not, fetch them from jira. It seems that this is the [endpoint](https://docs.atlassian.com/jira/REST/cloud/#api/2/issuetype-getIssueAllTypes) to use. 
* Save to configuration. To keep compatibility with current branch names we would have create a structure similar to the existing one, mapping each issue type to the first letter. I would index by id, but keep the type name so it is easier to know what each id represents:

```JSON
"jira": {
  "issueTypes": {
    "1234": {
      "name": "Bug",
      "shortName": "b"
    }
  }    
}
```

I can work on this, but if you wanna work on it, I would love to see a PR with it.

**Comment by alanpearce** [comment]
I tried taking a look, but I wasn't really sure where to start placing top-level code. Perhaps you could give me some pointers to get started, or, if you prefer, you could work on it and I could take a look afterwards, in order to get a better understanding of how things work here.

**Comment by tagoro9** [comment]
That sounds good. I should also document the code a little bit more. I haven't had much time this week, but I'll try to work on this next week.

**Comment by tagoro9** [comment]
Sorry that I took so long to fix this, but I haven't had much time to work on this. I just merged a PR that fixes this and adds support to define custom branch names.

**Comment by alanpearce** [comment]
No problem. I just hacked together some dumb modifications and `yarn link`ed it for my own use.
