### ISSUE TITLE
Can't extract branch name when using custom branch template

### ISSUE THREAD

**Issue by alanpearce** [tagoro9/fotingo#50]
With a branch template of simply `{issue.key}`, `fotingo review` can't extract the branch name.

It seems like the problem is the regex here: https://github.com/tagoro9/fotingo/blob/b5af3dcfdb16403f8d8c91f92d1f9f80fc5ec26d/src/git/util.js#L50

I'm not sure, but I had a thought about how to fix it: transform the keys used inside the template to matching regex fragments, leaving any symbols as they are (as anchors), so `{issue.key}` would be replaced with `(\w+-\d+)`

**Comment by alanpearce** [comment]
I think I might be able to do this. I've started with it; I will try to continue tomorrow. It might need a lot of review though 😄

**Comment by tagoro9** [comment]
Thanks so much for working on this! I should really give more priority to writing the tests (https://github.com/tagoro9/fotingo/issues/6). Maybe this way this could have been caught earlier. 

I like your idea!
