### ISSUE TITLE
Improve error handling when performin a release

### ISSUE THREAD

**Issue by llosimura** [tagoro9/fotingo#65]
When I perform a release with no release name the command goes through without any warning until it fails.

#### So, if I do:
`fotingo release`
#### I got:
<img width="914" alt="screen shot 2017-12-20 at 9 53 17 am" src="https://user-images.githubusercontent.com/1229306/34201790-93287cae-e56d-11e7-99b8-a6bbcceacb59.png">

The real issue comes when there are multiple related issues `-i` and no release name
#### Example
<img width="1000" alt="screen shot 2017-12-20 at 9 43 22 am" src="https://user-images.githubusercontent.com/1229306/34201923-048dd2c2-e56e-11e7-85b6-4cadbe70a5b1.png">

IMO this problem can be solved just by enforcing a release name to exist. Any thoughts on it? 
P.S: I ❤️  fotingo

**Comment by tagoro9** [comment]
Oops . It should definitely throw an error when this happens.
