### ISSUE TITLE
Support HTTPS remotes & authorization

### ISSUE THREAD

**Issue by eager** [tagoro9/fotingo#77]
For a few reasons, [GitHub recommends HTTPS cloning](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended)

**Comment by tagoro9** [comment]
This is now fixed in `2.0.0+` as it is no longer using `nodegit`, but instead some bindings on top of the native git command: https://github.com/steveukx/git-js
