### ISSUE TITLE
Fotingo freezes if there is no ssh key added 

### ISSUE THREAD

**Issue by llosimura** [tagoro9/fotingo#8]
If you forgot to execute `ssh-add -k ~/.ssh/id_rsa` it will hangout while creating the branch without giving the user any hint what is wrong.

**Comment by tagoro9** [comment]
This is a known issue not related to fotingo but to [nodegit](https://github.com/nodegit/nodegit/search?q=sshKeyFromAgent+hang&type=Issues&utf8=%E2%9C%93).

 I'm aware of that. It is explained on the [readme](https://github.com/tagoro9/fotingo#usage). It definitely sucks when you forget to add the ssh key and it hangs forever, but not much that I can do for now.

**Comment by llosimura** [comment]
Would it be possible at least to raise an error if the creation of the branch takes more than a predetermined time? At least it will show an error regardless what `nodegit` does.

**Comment by tagoro9** [comment]
It would be possible, but it would require a few changes on the way git authentication is done, as we need to keep track of the timeout. Not in my plans for now to fix this, but feel free to submit a PR with a fix.
